apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T15:27:20Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-test-production
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: test-production
    uid: f87a9d5f-526a-4ec7-9d78-51f4c5867336
  resourceVersion: "257395280"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-test-production
  uid: be93d369-4bee-40fb-a430-b4730286fcd8
spec:
  clusterIP: 172.30.104.61
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-test-production
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
