apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-08T13:55:43Z"
  name: srvc-claro-mock-service
  namespace: 3scale-project
  resourceVersion: "250787635"
  selfLink: /api/v1/namespaces/3scale-project/services/srvc-claro-mock-service
  uid: 7149afbd-de72-490b-83d9-994890b243ce
spec:
  clusterIP: 172.30.88.50
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: claro-mock-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
