apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: developer-ui
  name: system-developer
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378383"
  selfLink: /api/v1/namespaces/3scale-project/services/system-developer
  uid: 088feb48-c3f4-4291-96fa-a3931ac26d70
spec:
  clusterIP: 172.30.46.143
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: developer
  selector:
    deploymentConfig: system-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
