apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: provider-ui
  name: system-provider
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378374"
  selfLink: /api/v1/namespaces/3scale-project/services/system-provider
  uid: 046697dc-0cb8-4487-a6da-1fce77aa010f
spec:
  clusterIP: 172.30.118.50
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: provider
  selector:
    deploymentConfig: system-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
