apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: memcache
  name: system-memcache
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378390"
  selfLink: /api/v1/namespaces/3scale-project/services/system-memcache
  uid: a6294806-4bf0-447b-be17-55997edd9d54
spec:
  clusterIP: 172.30.96.59
  ports:
  - name: memcache
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    deploymentConfig: system-memcache
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
