apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T12:57:11Z"
  labels:
    name: threescale-operator
  name: threescale-operator
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: 3scale-operator
    uid: c13bcf25-e504-4fb8-ada8-0457fb994ca6
  resourceVersion: "198370901"
  selfLink: /api/v1/namespaces/3scale-project/services/threescale-operator
  uid: 8ef80c17-e652-4387-a685-edf3a6bef18a
spec:
  clusterIP: 172.30.17.250
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: threescale-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
