apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: zync
    threescale_component_element: database
  name: zync-database
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378432"
  selfLink: /api/v1/namespaces/3scale-project/services/zync-database
  uid: 286e40d3-1081-4b30-a32f-6256a1234c15
spec:
  clusterIP: 172.30.232.80
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deploymentConfig: zync-database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
