apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T15:38:13Z"
  name: apicast-openidc-policy-27-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-27-build
    uid: 005ada71-8b9b-4a57-ba8b-3fc2a54a5a3f
  resourceVersion: "246016574"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-27-sys-config
  uid: 8061e297-af80-4d4b-9239-91d2faa733c3
