apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-09T20:17:15Z"
  name: apicast-openidc-policy-30-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-30-build
    uid: b03cc9d2-bf7a-44a9-946a-a447afa967ee
  resourceVersion: "252207686"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-30-sys-config
  uid: bc6488e0-b52f-4834-92e9-c7ac4f408904
