apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-09T20:38:03Z"
  name: apicast-custom-policies-34-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-34-build
    uid: c4603726-e32b-4baa-b3b5-c337a1566e4a
  resourceVersion: "252224078"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-34-sys-config
  uid: 067519fe-2305-41ac-b7be-2ee6299ea301
