apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-07T15:21:44Z"
  name: apicast-openidc-policy-28-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-28-build
    uid: 67916fbd-f7da-4667-9129-6773249eb4ed
  resourceVersion: "249642030"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-28-sys-config
  uid: 3e620fa1-588c-44f0-9561-6a107e84e497
