apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T20:58:08Z"
  name: apicast-example-policy-5-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-example-policy-5-build
    uid: 40686ab3-2210-4ba7-ae36-3ed6f23a67fc
  resourceVersion: "237774370"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-example-policy-5-sys-config
  uid: 7283eecc-9613-48ec-8d01-1b0585e853de
