apiVersion: v1
data:
  APICAST_MANAGEMENT_API: status
  APICAST_RESPONSE_CODES: "true"
  OPENSSL_VERIFY: "false"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: apicast
  name: apicast-environment
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "259715117"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-environment
  uid: 903a9029-386e-48e6-a71f-b17cf1c5ba71
