apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-09T20:37:29Z"
  name: apicast-openidc-policy-33-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-33-build
    uid: eced6101-47d5-4a46-b6ce-089b784ad9ec
  resourceVersion: "252223598"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-33-sys-config
  uid: e973cb6b-b0b3-43ac-ba22-733a4a58348e
