apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T21:12:54Z"
  name: apicast-custom-policies-2-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-2-build
    uid: 35ba403a-e6aa-46eb-964b-0b338603395c
  resourceVersion: "237787007"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-2-sys-config
  uid: 3a973e84-16ee-49a8-8c71-e414a5d06d2d
