apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-09T20:18:24Z"
  name: apicast-openidc-policy-31-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-31-build
    uid: a4359d24-6b89-44d7-acb9-4b05286a8c2a
  resourceVersion: "252208661"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-31-sys-config
  uid: 955fb57d-632a-44f4-85cc-b08357c16772
