apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T20:53:13Z"
  name: apicast-example-policy-3-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-example-policy-3-build
    uid: 0db388af-1f0d-4a8f-b956-e17f0856fa61
  resourceVersion: "237770131"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-example-policy-3-sys-config
  uid: 21a82f52-181d-4039-aa79-67fb691388c8
