apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-09T20:33:32Z"
  name: apicast-custom-policies-33-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-33-build
    uid: 62f40829-204b-4395-b37e-28fb271db56f
  resourceVersion: "252220392"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-33-sys-config
  uid: bb0c0f43-ce17-40cf-b427-3d31eb0c984c
