apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T21:16:12Z"
  name: apicast-custom-policies-3-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-3-build
    uid: ff28e381-da37-4794-a3d0-d978a70d574d
  resourceVersion: "237789845"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-3-sys-config
  uid: 850a145f-4b50-4556-8828-8643d1a15236
