apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-31T14:02:12Z"
  name: apicast-custom-policies-5-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-5-build
    uid: b912a782-b342-47ad-bebd-68bf2e722368
  resourceVersion: "241067410"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-5-sys-config
  uid: 8d6df01d-da49-4518-9718-a482628778b2
