apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-09T20:17:35Z"
  name: apicast-custom-policies-32-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-32-build
    uid: 8a7d7fec-f43d-4573-8bf2-dde2969d7162
  resourceVersion: "252207922"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-32-sys-config
  uid: b7a61f7e-932a-4f50-b118-4d4f0edf6f01
