apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T20:40:18Z"
  name: apicast-example-policy-2-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-example-policy-2-build
    uid: 4269f548-5c44-4142-8cb2-704e0756a4d3
  resourceVersion: "237759197"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-example-policy-2-sys-config
  uid: 41c47a58-a97b-47fe-b505-d9fd7deee9a3
