apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-07T15:29:43Z"
  name: apicast-custom-policies-31-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-custom-policies-31-build
    uid: 73f2ed54-81b5-4082-b712-6956df46839b
  resourceVersion: "249649112"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-custom-policies-31-sys-config
  uid: 160fe2dd-6a7b-488f-8951-f3f02cf2de43
