apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-07T15:29:12Z"
  name: apicast-openidc-policy-29-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-29-build
    uid: 9c9795f1-0a3a-4216-a7e2-c6d9af90ee79
  resourceVersion: "249648634"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-29-sys-config
  uid: ab4a42a8-ee4d-4ee5-97a0-97e6eee98908
