apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T19:58:53Z"
  name: apicast-openidc-policy-2-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: apicast-openidc-policy-2-build
    uid: deb29767-4d45-4c54-ac61-0e27b12160ba
  resourceVersion: "237723971"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/apicast-openidc-policy-2-sys-config
  uid: 42b1805a-8b93-416e-a64d-f3484020efff
