apiVersion: v1
data:
  RACK_ENV: production
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: backend
  name: backend-environment
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378364"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/backend-environment
  uid: a61f9565-392e-4fa1-8ad4-fea96d47bbf7
