apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-08T15:07:36Z"
  name: book-service-1-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: book-service-1-build
    uid: fdff0124-9637-443a-967c-bed68add789a
  resourceVersion: "250848808"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/book-service-1-sys-config
  uid: d5ef8b1b-0741-4df0-9a3c-51f60a7457b4
