apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-08T15:40:55Z"
  name: book-service-3-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: book-service-3-build
    uid: ca3de2d0-d526-41f4-8af9-b7638040a8ce
  resourceVersion: "250880141"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/book-service-3-sys-config
  uid: c84a9059-29de-49a3-bc90-8d488914a876
