apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-07T21:46:53Z"
  name: claro-mock-service-4-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: claro-mock-service-4-build
    uid: 0f642e6c-6f0d-4397-9beb-748fe76f9e96
  resourceVersion: "249969536"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/claro-mock-service-4-sys-config
  uid: 69a0dda2-07c0-4346-91e1-fdca892b618a
