apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-07T21:49:15Z"
  name: claro-mock-service-5-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: claro-mock-service-5-build
    uid: e2d8fcec-eb3e-43f6-a613-980e350da133
  resourceVersion: "249971523"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/claro-mock-service-5-sys-config
  uid: 1c084697-97af-4955-88bd-4365014ddc68
