apiVersion: v1
data:
  policy.json: '{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"docker.io":[{"type":"reject"}]},"docker":{"docker.io":[{"type":"reject"}]}}}'
  registries.conf: |
    unqualified-search-registries = ["docker.io"]

    [[registry]]
      prefix = ""
      location = "docker.io"
      blocked = true
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-07T21:04:24Z"
  name: claro-mock-service-1-sys-config
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: claro-mock-service-1-build
    uid: 3883844a-c559-45a2-b281-4b33a2536f9f
  resourceVersion: "249932397"
  selfLink: /api/v1/namespaces/3scale-project/configmaps/claro-mock-service-1-sys-config
  uid: d3cf46a0-be99-4383-8da0-51b4fa57665d
