apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      deployment; cpu, memory limit for container deployment'
    openshift.io/deployment-config.name: apicast-staging
    openshift.io/deployment.name: apicast-staging-31
    openshift.io/scc: restricted
  creationTimestamp: "2020-09-07T15:30:11Z"
  labels:
    openshift.io/deployer-pod-for.name: apicast-staging-31
  name: apicast-staging-31-deploy
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: ReplicationController
    name: apicast-staging-31
    uid: 3b49df5c-aa3e-483e-8afc-74006a7efc25
  resourceVersion: "249650616"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-staging-31-deploy
  uid: 3d5b1e05-cf58-413e-9d51-1c2e6c20fe6c
spec:
  activeDeadlineSeconds: 21600
  containers:
  - env:
    - name: OPENSHIFT_DEPLOYMENT_NAME
      value: apicast-staging-31
    - name: OPENSHIFT_DEPLOYMENT_NAMESPACE
      value: 3scale-project
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imagePullPolicy: IfNotPresent
    name: deployment
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployer-token-679s7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: deployer-dockercfg-dl94k
  nodeName: infra-01.osepext01.claro.amx
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: deployer
  serviceAccountName: deployer
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: deployer-token-679s7
    secret:
      defaultMode: 420
      secretName: deployer-token-679s7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:30:11Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:31:03Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:31:03Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:30:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://fd2e94b92a7c12dedc250ef422a4e6d3e2bb7a757dcda7b3a55be81355cf7d2e
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://fd2e94b92a7c12dedc250ef422a4e6d3e2bb7a757dcda7b3a55be81355cf7d2e
        exitCode: 0
        finishedAt: "2020-09-07T15:31:03Z"
        reason: Completed
        startedAt: "2020-09-07T15:30:14Z"
  hostIP: 10.92.114.128
  phase: Succeeded
  podIP: 10.128.0.245
  podIPs:
  - ip: 10.128.0.245
  qosClass: Burstable
  startTime: "2020-09-07T15:30:11Z"
