apiVersion: v1
kind: Pod
metadata:
  annotations:
    apicast.apps.3scale.net/admin-portal-secret-resource-version: "257374567"
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.4.190"
          ],
          "dns": {},
          "default-route": [
              "10.128.4.1"
          ]
      }]
    openshift.io/scc: restricted
    prometheus.io/port: "9421"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-09-14T14:59:47Z"
  generateName: apicast-dev-staging-5bc85bbcb6-
  labels:
    deployment: apicast-dev-staging
    pod-template-hash: 5bc85bbcb6
  name: apicast-dev-staging-5bc85bbcb6-kg299
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apicast-dev-staging-5bc85bbcb6
    uid: 35f42d52-bd45-4438-aad6-854f6bf7612e
  resourceVersion: "257374820"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-dev-staging-5bc85bbcb6-kg299
  uid: 90940ab0-cdb3-4917-83cb-11a8c382d0dd
spec:
  containers:
  - env:
    - name: THREESCALE_PORTAL_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: AdminPortalURL
          name: apicastdev-staging-secret
    - name: THREESCALE_DEPLOYMENT_ENV
      value: staging
    - name: APICAST_CONFIGURATION_LOADER
      value: lazy
    - name: APICAST_CONFIGURATION_CACHE
      value: "0"
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /status/live
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: apicast-dev-staging
    ports:
    - containerPort: 8080
      name: proxy
      protocol: TCP
    - containerPort: 8090
      name: management
      protocol: TCP
    - containerPort: 9421
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /status/ready
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 64Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-fc8nn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-h648n
  nodeName: worker-03.osepext01.claro.amx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-fc8nn
    secret:
      defaultMode: 420
      secretName: default-token-fc8nn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T14:59:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T15:00:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T15:00:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T14:59:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://75889c33a2cfa0997ad8ceb5c4ca244c6c8d223574b52b30378f8fd008116642
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    imageID: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    lastState: {}
    name: apicast-dev-staging
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-14T14:59:51Z"
  hostIP: 10.92.114.133
  phase: Running
  podIP: 10.128.4.190
  podIPs:
  - ip: 10.128.4.190
  qosClass: Burstable
  startTime: "2020-09-14T14:59:47Z"
