apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      sti-build; cpu, memory limit for container sti-build; cpu, memory request for
      init container git-clone; cpu, memory limit for init container git-clone; cpu,
      memory request for init container manage-dockerfile; cpu, memory limit for init
      container manage-dockerfile'
    openshift.io/build.name: apicast-openidc-policy-28
    openshift.io/scc: privileged
  creationTimestamp: "2020-09-07T15:21:44Z"
  labels:
    openshift.io/build.name: apicast-openidc-policy-28
  name: apicast-openidc-policy-28-build
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: apicast-openidc-policy-28
    uid: 3ab8597f-ae83-4419-be33-41f65c2a54c8
  resourceVersion: "249642642"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-openidc-policy-28-build
  uid: 67916fbd-f7da-4667-9129-6773249eb4ed
spec:
  activeDeadlineSeconds: 604800
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"apicast-openidc-policy-28","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/apicast-openidc-policy-28","uid":"3ab8597f-ae83-4419-be33-41f65c2a54c8","resourceVersion":"249642022","creationTimestamp":"2020-09-07T15:21:43Z","labels":{"app":"apicast","buildconfig":"apicast-openidc-policy","openshift.io/build-config.name":"apicast-openidc-policy","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"apicast-openidc-policy","openshift.io/build.number":"28"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"apicast-openidc-policy","uid":"e6552f7e-3319-4287-b3e4-00a9ec8f6f22","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/rohdrigo77/apicast-example-policy.git","ref":"master"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/apicast-policy:openidc"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Manually triggered"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/apicast-policy:openidc","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"apicast-openidc-policy"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: SOURCE_REPOSITORY
      value: https://github.com/rohdrigo77/apicast-example-policy.git
    - name: SOURCE_URI
      value: https://github.com/rohdrigo77/apicast-example-policy.git
    - name: SOURCE_REF
      value: master
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    - name: PULL_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/pull
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_STORAGE_DRIVER
      value: overlay
    - name: BUILD_ISOLATION
      value: chroot
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/lib/containers/cache
      name: buildcachedir
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-jtvsh-push
      readOnly: true
    - mountPath: /var/run/secrets/openshift.io/pull
      name: builder-dockercfg-jtvsh-pull
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/lib/containers/storage
      name: container-storage-root
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: builder-dockercfg-jtvsh
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"apicast-openidc-policy-28","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/apicast-openidc-policy-28","uid":"3ab8597f-ae83-4419-be33-41f65c2a54c8","resourceVersion":"249642022","creationTimestamp":"2020-09-07T15:21:43Z","labels":{"app":"apicast","buildconfig":"apicast-openidc-policy","openshift.io/build-config.name":"apicast-openidc-policy","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"apicast-openidc-policy","openshift.io/build.number":"28"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"apicast-openidc-policy","uid":"e6552f7e-3319-4287-b3e4-00a9ec8f6f22","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/rohdrigo77/apicast-example-policy.git","ref":"master"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/apicast-policy:openidc"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Manually triggered"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/apicast-policy:openidc","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"apicast-openidc-policy"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: SOURCE_REPOSITORY
      value: https://github.com/rohdrigo77/apicast-example-policy.git
    - name: SOURCE_URI
      value: https://github.com/rohdrigo77/apicast-example-policy.git
    - name: SOURCE_REF
      value: master
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"apicast-openidc-policy-28","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/apicast-openidc-policy-28","uid":"3ab8597f-ae83-4419-be33-41f65c2a54c8","resourceVersion":"249642022","creationTimestamp":"2020-09-07T15:21:43Z","labels":{"app":"apicast","buildconfig":"apicast-openidc-policy","openshift.io/build-config.name":"apicast-openidc-policy","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"apicast-openidc-policy","openshift.io/build.number":"28"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"apicast-openidc-policy","uid":"e6552f7e-3319-4287-b3e4-00a9ec8f6f22","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/rohdrigo77/apicast-example-policy.git","ref":"master"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/apicast-policy:openidc"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Manually triggered"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/apicast-policy:openidc","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"apicast-openidc-policy"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: SOURCE_REPOSITORY
      value: https://github.com/rohdrigo77/apicast-example-policy.git
    - name: SOURCE_URI
      value: https://github.com/rohdrigo77/apicast-example-policy.git
    - name: SOURCE_REF
      value: master
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  nodeName: infra-01.osepext01.claro.amx
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/containers/cache
      type: ""
    name: buildcachedir
  - emptyDir: {}
    name: buildworkdir
  - name: builder-dockercfg-jtvsh-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-jtvsh
  - name: builder-dockercfg-jtvsh-pull
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-jtvsh
  - configMap:
      defaultMode: 420
      name: apicast-openidc-policy-28-sys-config
    name: build-system-configs
  - configMap:
      defaultMode: 420
      items:
      - key: service-ca.crt
        path: certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt
      name: apicast-openidc-policy-28-ca
    name: build-ca-bundles
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: apicast-openidc-policy-28-global-ca
    name: build-proxy-ca-bundles
  - emptyDir: {}
    name: container-storage-root
  - emptyDir: {}
    name: build-blob-cache
  - name: builder-token-gv4x9
    secret:
      defaultMode: 420
      secretName: builder-token-gv4x9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:21:50Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:22:14Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:22:14Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T15:21:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://3dfaf0614d2ebd7b7a84eb71ab937b7d9e55f9fe69b47808495f85a04e112928
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: sti-build
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://3dfaf0614d2ebd7b7a84eb71ab937b7d9e55f9fe69b47808495f85a04e112928
        exitCode: 0
        finishedAt: "2020-09-07T15:22:13Z"
        reason: Completed
        startedAt: "2020-09-07T15:21:50Z"
  hostIP: 10.92.114.128
  initContainerStatuses:
  - containerID: cri-o://853206c5e8b2aab94d0920dd92e5c0ea05bd44f9f044473bdcf5bae1d917233a
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: git-clone
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://853206c5e8b2aab94d0920dd92e5c0ea05bd44f9f044473bdcf5bae1d917233a
        exitCode: 0
        finishedAt: "2020-09-07T15:21:48Z"
        reason: Completed
        startedAt: "2020-09-07T15:21:45Z"
  - containerID: cri-o://0c4c5d6dd3428d738ba4413cbf886fce33ac9a5533fd4d0a2e6eafe06c02fc84
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: manage-dockerfile
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://0c4c5d6dd3428d738ba4413cbf886fce33ac9a5533fd4d0a2e6eafe06c02fc84
        exitCode: 0
        finishedAt: "2020-09-07T15:21:49Z"
        reason: Completed
        startedAt: "2020-09-07T15:21:49Z"
  phase: Succeeded
  podIP: 10.128.0.239
  podIPs:
  - ip: 10.128.0.239
  qosClass: Burstable
  startTime: "2020-09-07T15:21:43Z"
