apiVersion: v1
kind: Pod
metadata:
  annotations:
    apicast.apps.3scale.net/admin-portal-secret-resource-version: "254094449"
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.131.3.47"
          ],
          "dns": {},
          "default-route": [
              "10.131.2.1"
          ]
      }]
    openshift.io/scc: restricted
    prometheus.io/port: "9421"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-09-11T15:40:44Z"
  generateName: apicast-apicast-production-dev-569c594c88-
  labels:
    deployment: apicast-apicast-production-dev
    pod-template-hash: 569c594c88
  name: apicast-apicast-production-dev-569c594c88-dhnb4
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apicast-apicast-production-dev-569c594c88
    uid: ae278f4e-1107-4628-9701-304ba52529e5
  resourceVersion: "254155215"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-apicast-production-dev-569c594c88-dhnb4
  uid: 77eca960-ba9a-40b2-8adf-c184735d00c1
spec:
  containers:
  - env:
    - name: THREESCALE_PORTAL_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: AdminPortalURL
          name: apicast-dev-production-secret
    - name: THREESCALE_DEPLOYMENT_ENV
      value: staging
    - name: APICAST_CONFIGURATION_LOADER
      value: lazy
    - name: APICAST_CONFIGURATION_CACHE
      value: "0"
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /status/live
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: apicast-apicast-production-dev
    ports:
    - containerPort: 8080
      name: proxy
      protocol: TCP
    - containerPort: 8090
      name: management
      protocol: TCP
    - containerPort: 9421
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /status/ready
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 64Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-fc8nn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-h648n
  nodeName: worker-02.osepext01.claro.amx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-fc8nn
    secret:
      defaultMode: 420
      secretName: default-token-fc8nn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T15:40:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T15:41:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T15:41:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T15:40:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://3ce517e4e62a60e9a6d4311b860c74aa606586931384eed540c74e40f8a16d69
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    imageID: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    lastState: {}
    name: apicast-apicast-production-dev
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-11T15:40:48Z"
  hostIP: 10.92.114.132
  phase: Running
  podIP: 10.131.3.47
  podIPs:
  - ip: 10.131.3.47
  qosClass: Burstable
  startTime: "2020-09-11T15:40:44Z"
