apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      deployment; cpu, memory limit for container deployment'
    openshift.io/deployment-config.name: apicast-staging
    openshift.io/deployment.name: apicast-staging-28
    openshift.io/scc: restricted
  creationTimestamp: "2020-09-03T22:11:21Z"
  labels:
    openshift.io/deployer-pod-for.name: apicast-staging-28
  name: apicast-staging-28-deploy
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: ReplicationController
    name: apicast-staging-28
    uid: 90a19c56-5edb-483f-80a7-8aea27150311
  resourceVersion: "245133584"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-staging-28-deploy
  uid: 2f500fb4-44b5-4b25-9673-c468e7e317eb
spec:
  activeDeadlineSeconds: 21600
  containers:
  - env:
    - name: OPENSHIFT_DEPLOYMENT_NAME
      value: apicast-staging-28
    - name: OPENSHIFT_DEPLOYMENT_NAMESPACE
      value: 3scale-project
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imagePullPolicy: IfNotPresent
    name: deployment
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployer-token-679s7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: deployer-dockercfg-dl94k
  nodeName: infra-03.osepext01.claro.amx
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: deployer
  serviceAccountName: deployer
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: deployer-token-679s7
    secret:
      defaultMode: 420
      secretName: deployer-token-679s7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-03T22:11:22Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-03T22:11:58Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-03T22:11:58Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-03T22:11:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://c78ee9617ca37b6d83e52c4368159e82e65a0e8440ab1a2a88b253e76c3951b2
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://c78ee9617ca37b6d83e52c4368159e82e65a0e8440ab1a2a88b253e76c3951b2
        exitCode: 0
        finishedAt: "2020-09-03T22:11:58Z"
        reason: Completed
        startedAt: "2020-09-03T22:11:24Z"
  hostIP: 10.92.114.130
  phase: Succeeded
  podIP: 10.129.3.241
  podIPs:
  - ip: 10.129.3.241
  qosClass: Burstable
  startTime: "2020-09-03T22:11:22Z"
