apiVersion: v1
kind: Pod
metadata:
  annotations:
    apicast.apps.3scale.net/admin-portal-secret-resource-version: "257404458"
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.131.3.49"
          ],
          "dns": {},
          "default-route": [
              "10.131.2.1"
          ]
      }]
    openshift.io/scc: restricted
    prometheus.io/port: "9421"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-09-14T15:39:08Z"
  generateName: apicast-prod-production-854f6486dd-
  labels:
    deployment: apicast-prod-production
    pod-template-hash: 854f6486dd
  name: apicast-prod-production-854f6486dd-2s5pn
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apicast-prod-production-854f6486dd
    uid: 76937646-2d03-44a5-bd3a-45abc20b281b
  resourceVersion: "257405092"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-prod-production-854f6486dd-2s5pn
  uid: c0d673cd-354a-404f-bf21-c2c22c142868
spec:
  containers:
  - env:
    - name: THREESCALE_PORTAL_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: AdminPortalURL
          name: apicastprod-production-secret
    - name: THREESCALE_DEPLOYMENT_ENV
      value: production
    - name: APICAST_CONFIGURATION_LOADER
      value: boot
    - name: APICAST_CONFIGURATION_CACHE
      value: "300"
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /status/live
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: apicast-prod-production
    ports:
    - containerPort: 8080
      name: proxy
      protocol: TCP
    - containerPort: 8090
      name: management
      protocol: TCP
    - containerPort: 9421
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /status/ready
        port: 8090
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 64Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-fc8nn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-h648n
  nodeName: worker-02.osepext01.claro.amx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-fc8nn
    secret:
      defaultMode: 420
      secretName: default-token-fc8nn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T15:39:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T15:39:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T15:39:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-14T15:39:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://26ba121bfe7a4143c017b00e87ac4850c32121ed40e4448bd611ab9910653b33
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    imageID: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    lastState: {}
    name: apicast-prod-production
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-14T15:39:11Z"
  hostIP: 10.92.114.132
  phase: Running
  podIP: 10.131.3.49
  podIPs:
  - ip: 10.131.3.49
  qosClass: Burstable
  startTime: "2020-09-14T15:39:07Z"
