apiVersion: v1
kind: Pod
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"apps.3scale.net/v1alpha1","kind":"APIcast","metadata":{"name":"example-apicast"},"spec":{"adminPortalCredentialsRef":{"name":"mysecretname"}}},
      {"apiVersion":"apps.3scale.net/v1alpha1","kind":"APIcast","metadata":{"name":"example-apicast"},"spec":{"embeddedConfigurationSecretRef":{"name":"mysecretname"}}}]'
    capabilities: Full Lifecycle
    categories: Integration & Delivery
    certified: "false"
    containerImage: registry.redhat.io/3scale-amp2/apicast-rhel7-operator@sha256:bcf2f453d7f828ad9df2a29e31cde4b4d3bd08b1205e1928b8362d7331854761
    createdAt: "2019-10-27T22:40:00Z"
    description: APIcast is an API gateway to be used together with Red Hat 3scale
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.4.230"
          ],
          "dns": {},
          "default-route": [
              "10.129.4.1"
          ]
      }]
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      apicast-operator; cpu, memory limit for container apicast-operator'
    olm.operatorGroup: 3scale-project-h5p24
    olm.operatorNamespace: 3scale-project
    olm.targetNamespaces: 3scale-project
    openshift.io/scc: restricted
    repository: https://github.com/3scale/apicast-operator
    support: Red Hat, Inc.
    tectonic-visibility: ocs
  creationTimestamp: "2020-09-09T20:05:17Z"
  generateName: apicast-operator-7b4998676-
  labels:
    name: apicast-operator
    pod-template-hash: 7b4998676
  name: apicast-operator-7b4998676-rhtnc
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: apicast-operator-7b4998676
    uid: 7a5be6a7-dbf0-45ee-9218-3f8a3a31553e
  resourceVersion: "252198428"
  selfLink: /api/v1/namespaces/3scale-project/pods/apicast-operator-7b4998676-rhtnc
  uid: 4cd6a069-0a68-42ea-b242-e3a76acb017f
spec:
  containers:
  - command:
    - apicast-operator
    env:
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OPERATOR_NAME
      value: apicast-operator
    - name: APICAST_IMAGE
      value: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:3023b37ccfc902bfafd2c344dc5595295369a2dc00ea38b27c193ca5b138942b
    image: registry.redhat.io/3scale-amp2/apicast-rhel7-operator@sha256:bcf2f453d7f828ad9df2a29e31cde4b4d3bd08b1205e1928b8362d7331854761
    imagePullPolicy: IfNotPresent
    name: apicast-operator
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: apicast-operator-token-qpx9t
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: apicast-operator-dockercfg-mjbtv
  nodeName: worker-04.osepext01.claro.amx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: apicast-operator
  serviceAccountName: apicast-operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: apicast-operator-token-qpx9t
    secret:
      defaultMode: 420
      secretName: apicast-operator-token-qpx9t
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-09T20:05:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-09T20:05:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-09T20:05:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-09T20:05:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://e815be3a32bb9efe4a0833010a12eebd7e81ab5ace25bf41978bd0a522c2d9fb
    image: registry.redhat.io/3scale-amp2/apicast-rhel7-operator@sha256:bcf2f453d7f828ad9df2a29e31cde4b4d3bd08b1205e1928b8362d7331854761
    imageID: registry.redhat.io/3scale-amp2/apicast-rhel7-operator@sha256:bcf2f453d7f828ad9df2a29e31cde4b4d3bd08b1205e1928b8362d7331854761
    lastState: {}
    name: apicast-operator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-09T20:05:19Z"
  hostIP: 10.92.114.134
  phase: Running
  podIP: 10.129.4.230
  podIPs:
  - ip: 10.129.4.230
  qosClass: Burstable
  startTime: "2020-09-09T20:05:17Z"
