apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      deployment; cpu, memory limit for container deployment'
    openshift.io/deployment-config.name: backend-cron
    openshift.io/deployment.name: backend-cron-2
    openshift.io/scc: restricted
  creationTimestamp: "2020-07-27T15:13:21Z"
  labels:
    openshift.io/deployer-pod-for.name: backend-cron-2
  name: backend-cron-2-deploy
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: ReplicationController
    name: backend-cron-2
    uid: fb0a3ca1-4cd1-4dd6-b2f3-a6d20e9922bf
  resourceVersion: "198488670"
  selfLink: /api/v1/namespaces/3scale-project/pods/backend-cron-2-deploy
  uid: 64c5454e-79cc-425e-afb0-f2b948e99127
spec:
  activeDeadlineSeconds: 21600
  containers:
  - env:
    - name: OPENSHIFT_DEPLOYMENT_NAME
      value: backend-cron-2
    - name: OPENSHIFT_DEPLOYMENT_NAMESPACE
      value: 3scale-project
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imagePullPolicy: IfNotPresent
    name: deployment
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployer-token-679s7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: deployer-dockercfg-dl94k
  nodeName: infra-01.osepext01.claro.amx
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: deployer
  serviceAccountName: deployer
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: deployer-token-679s7
    secret:
      defaultMode: 420
      secretName: deployer-token-679s7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-27T15:13:21Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-07-27T15:13:35Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-07-27T15:13:35Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-07-27T15:13:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://e7a626ca45e2d17029fa8dbf7101ab26e2b6a9acc4981d319a4e9225572c28c0
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://e7a626ca45e2d17029fa8dbf7101ab26e2b6a9acc4981d319a4e9225572c28c0
        exitCode: 0
        finishedAt: "2020-07-27T15:13:34Z"
        reason: Completed
        startedAt: "2020-07-27T15:13:24Z"
  hostIP: 10.92.114.128
  phase: Succeeded
  podIP: 10.128.0.59
  podIPs:
  - ip: 10.128.0.59
  qosClass: Burstable
  startTime: "2020-07-27T15:13:21Z"
