apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      deployment; cpu, memory limit for container deployment'
    openshift.io/deployment-config.name: book-service
    openshift.io/deployment.name: book-service-1
    openshift.io/scc: restricted
  creationTimestamp: "2020-09-08T15:41:31Z"
  labels:
    openshift.io/deployer-pod-for.name: book-service-1
  name: book-service-1-deploy
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: ReplicationController
    name: book-service-1
    uid: c43e1655-8091-4046-beeb-8d9a68b52121
  resourceVersion: "250881000"
  selfLink: /api/v1/namespaces/3scale-project/pods/book-service-1-deploy
  uid: 13d95441-c4e4-4a9c-a469-fda8378085e8
spec:
  activeDeadlineSeconds: 21600
  containers:
  - env:
    - name: OPENSHIFT_DEPLOYMENT_NAME
      value: book-service-1
    - name: OPENSHIFT_DEPLOYMENT_NAMESPACE
      value: 3scale-project
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imagePullPolicy: IfNotPresent
    name: deployment
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployer-token-679s7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: deployer-dockercfg-dl94k
  nodeName: worker-02.osepext01.claro.amx
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: deployer
  serviceAccountName: deployer
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: deployer-token-679s7
    secret:
      defaultMode: 420
      secretName: deployer-token-679s7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-08T15:41:31Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-08T15:41:49Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-08T15:41:49Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-08T15:41:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://4918526ebd6d3a4c7ffcf2cc119c402dba7b145985235ca21af0bcc188d82284
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://4918526ebd6d3a4c7ffcf2cc119c402dba7b145985235ca21af0bcc188d82284
        exitCode: 0
        finishedAt: "2020-09-08T15:41:49Z"
        reason: Completed
        startedAt: "2020-09-08T15:41:34Z"
  hostIP: 10.92.114.132
  phase: Succeeded
  podIP: 10.131.3.18
  podIPs:
  - ip: 10.131.3.18
  qosClass: Burstable
  startTime: "2020-09-08T15:41:31Z"
