apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      sti-build; cpu, memory limit for container sti-build; cpu, memory request for
      init container git-clone; cpu, memory limit for init container git-clone; cpu,
      memory request for init container manage-dockerfile; cpu, memory limit for init
      container manage-dockerfile'
    openshift.io/build.name: claro-mock-service-2
    openshift.io/scc: privileged
  creationTimestamp: "2020-09-07T21:14:33Z"
  labels:
    openshift.io/build.name: claro-mock-service-2
  name: claro-mock-service-2-build
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: claro-mock-service-2
    uid: 8db399ee-9997-4bbf-9156-c09e2e749887
  resourceVersion: "249941957"
  selfLink: /api/v1/namespaces/3scale-project/pods/claro-mock-service-2-build
  uid: aaab6513-fb14-43fe-961b-9ac07c725001
spec:
  activeDeadlineSeconds: 604800
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"claro-mock-service-2","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/claro-mock-service-2","uid":"8db399ee-9997-4bbf-9156-c09e2e749887","resourceVersion":"249940971","creationTimestamp":"2020-09-07T21:14:33Z","labels":{"build":"claro-mock-service","buildconfig":"claro-mock-service","openshift.io/build-config.name":"claro-mock-service","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"claro-mock-service","openshift.io/build.number":"2"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"claro-mock-service","uid":"e9570f67-9198-4571-b424-9b0e8aadb30e","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.redhat.io/fuse7/fuse-java-openshift@sha256:df0102150f7065d64a11c35091e8d41fa208e9a372c69e5a81638f62f8a1569d"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"claro-mock-service"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    - name: PULL_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/pull
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_STORAGE_DRIVER
      value: overlay
    - name: BUILD_ISOLATION
      value: chroot
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/lib/containers/cache
      name: buildcachedir
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-jtvsh-push
      readOnly: true
    - mountPath: /var/run/secrets/openshift.io/pull
      name: builder-dockercfg-jtvsh-pull
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/lib/containers/storage
      name: container-storage-root
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: builder-dockercfg-jtvsh
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-git-clone
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"claro-mock-service-2","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/claro-mock-service-2","uid":"8db399ee-9997-4bbf-9156-c09e2e749887","resourceVersion":"249940971","creationTimestamp":"2020-09-07T21:14:33Z","labels":{"build":"claro-mock-service","buildconfig":"claro-mock-service","openshift.io/build-config.name":"claro-mock-service","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"claro-mock-service","openshift.io/build.number":"2"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"claro-mock-service","uid":"e9570f67-9198-4571-b424-9b0e8aadb30e","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.redhat.io/fuse7/fuse-java-openshift@sha256:df0102150f7065d64a11c35091e8d41fa208e9a372c69e5a81638f62f8a1569d"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"claro-mock-service"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"claro-mock-service-2","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/claro-mock-service-2","uid":"8db399ee-9997-4bbf-9156-c09e2e749887","resourceVersion":"249940971","creationTimestamp":"2020-09-07T21:14:33Z","labels":{"build":"claro-mock-service","buildconfig":"claro-mock-service","openshift.io/build-config.name":"claro-mock-service","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"claro-mock-service","openshift.io/build.number":"2"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"claro-mock-service","uid":"e9570f67-9198-4571-b424-9b0e8aadb30e","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Binary","binary":{}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"registry.redhat.io/fuse7/fuse-java-openshift@sha256:df0102150f7065d64a11c35091e8d41fa208e9a372c69e5a81638f62f8a1569d"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":null},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"claro-mock-service"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  nodeName: infra-01.osepext01.claro.amx
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/containers/cache
      type: ""
    name: buildcachedir
  - emptyDir: {}
    name: buildworkdir
  - name: builder-dockercfg-jtvsh-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-jtvsh
  - name: builder-dockercfg-jtvsh-pull
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-jtvsh
  - configMap:
      defaultMode: 420
      name: claro-mock-service-2-sys-config
    name: build-system-configs
  - configMap:
      defaultMode: 420
      items:
      - key: service-ca.crt
        path: certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt
      name: claro-mock-service-2-ca
    name: build-ca-bundles
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: claro-mock-service-2-global-ca
    name: build-proxy-ca-bundles
  - emptyDir: {}
    name: container-storage-root
  - emptyDir: {}
    name: build-blob-cache
  - name: builder-token-gv4x9
    secret:
      defaultMode: 420
      secretName: builder-token-gv4x9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:15:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:15:35Z"
    message: 'containers with unready status: [sti-build]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:15:35Z"
    message: 'containers with unready status: [sti-build]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:14:33Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://20c34853f7bcb7b80c41696ceb32691d236431e6aa7e6f8a3f87103eadf1bad4
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: sti-build
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://20c34853f7bcb7b80c41696ceb32691d236431e6aa7e6f8a3f87103eadf1bad4
        exitCode: 1
        finishedAt: "2020-09-07T21:15:35Z"
        message: |
          Caching blobs under "/var/cache/blobs".
          Warning: Pull failed, retrying in 5s ...
          Warning: Pull failed, retrying in 5s ...
          Warning: Pull failed, retrying in 5s ...
          error: build error: After retrying 2 times, Pull image still failed due to error: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
        reason: Error
        startedAt: "2020-09-07T21:15:18Z"
  hostIP: 10.92.114.128
  initContainerStatuses:
  - containerID: cri-o://1e24b66339f86a529b6bb9f1fd1e3882b86b0412230df4ae0e230ea0f7e160bd
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: git-clone
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://1e24b66339f86a529b6bb9f1fd1e3882b86b0412230df4ae0e230ea0f7e160bd
        exitCode: 0
        finishedAt: "2020-09-07T21:15:17Z"
        reason: Completed
        startedAt: "2020-09-07T21:14:36Z"
  - containerID: cri-o://b0f869c4be23edfe649d04c5575eba0d0dbef4c3db661b4aabdde6dfa40f90d0
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: manage-dockerfile
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://b0f869c4be23edfe649d04c5575eba0d0dbef4c3db661b4aabdde6dfa40f90d0
        exitCode: 0
        finishedAt: "2020-09-07T21:15:17Z"
        reason: Completed
        startedAt: "2020-09-07T21:15:17Z"
  phase: Failed
  podIP: 10.128.1.21
  podIPs:
  - ip: 10.128.1.21
  qosClass: Burstable
  startTime: "2020-09-07T21:14:32Z"
