apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      sti-build; cpu, memory limit for container sti-build; cpu, memory request for
      init container manage-dockerfile; cpu, memory limit for init container manage-dockerfile'
    openshift.io/build.name: claro-mock-service-3
    openshift.io/scc: privileged
  creationTimestamp: "2020-09-07T21:46:14Z"
  labels:
    openshift.io/build.name: claro-mock-service-3
  name: claro-mock-service-3-build
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    controller: true
    kind: Build
    name: claro-mock-service-3
    uid: 37ed354f-07cc-44e2-9327-0fb62d463d98
  resourceVersion: "249969685"
  selfLink: /api/v1/namespaces/3scale-project/pods/claro-mock-service-3-build
  uid: 7afe43f2-559e-4841-96a4-e1f91e14ddf8
spec:
  activeDeadlineSeconds: 604800
  containers:
  - args:
    - --loglevel=0
    command:
    - openshift-sti-build
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"claro-mock-service-3","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/claro-mock-service-3","uid":"37ed354f-07cc-44e2-9327-0fb62d463d98","resourceVersion":"249968907","creationTimestamp":"2020-09-07T21:46:14Z","labels":{"build":"claro-mock-service","buildconfig":"claro-mock-service","openshift.io/build-config.name":"claro-mock-service","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"claro-mock-service","openshift.io/build.number":"3"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"claro-mock-service","uid":"e9570f67-9198-4571-b424-9b0e8aadb30e","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"None"},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"fuse7-java-openshift:1.5"}}}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"claro-mock-service"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: PUSH_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/push
    - name: PULL_DOCKERCFG_PATH
      value: /var/run/secrets/openshift.io/pull
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_STORAGE_DRIVER
      value: overlay
    - name: BUILD_ISOLATION
      value: chroot
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: sti-build
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/lib/containers/cache
      name: buildcachedir
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-jtvsh-push
      readOnly: true
    - mountPath: /var/run/secrets/openshift.io/pull
      name: builder-dockercfg-jtvsh-pull
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/lib/containers/storage
      name: container-storage-root
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: builder-dockercfg-jtvsh
  initContainers:
  - args:
    - --loglevel=0
    command:
    - openshift-manage-dockerfile
    env:
    - name: BUILD
      value: |
        {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"claro-mock-service-3","namespace":"3scale-project","selfLink":"/apis/build.openshift.io/v1/namespaces/3scale-project/builds/claro-mock-service-3","uid":"37ed354f-07cc-44e2-9327-0fb62d463d98","resourceVersion":"249968907","creationTimestamp":"2020-09-07T21:46:14Z","labels":{"build":"claro-mock-service","buildconfig":"claro-mock-service","openshift.io/build-config.name":"claro-mock-service","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"claro-mock-service","openshift.io/build.number":"3"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"claro-mock-service","uid":"e9570f67-9198-4571-b424-9b0e8aadb30e","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"None"},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b"},"pullSecret":{"name":"builder-dockercfg-jtvsh"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0"},"pushSecret":{"name":"builder-dockercfg-jtvsh"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Image change","imageChangeBuild":{"imageID":"image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b","fromRef":{"kind":"ImageStreamTag","namespace":"openshift","name":"fuse7-java-openshift:1.5"}}}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/3scale-project/claro-mock-service:1.0","config":{"kind":"BuildConfig","namespace":"3scale-project","name":"claro-mock-service"},"output":{}}}
    - name: LANG
      value: en_US.utf8
    - name: ALLOWED_UIDS
      value: 1-
    - name: DROP_CAPS
      value: KILL,MKNOD,SETGID,SETUID
    - name: BUILD_REGISTRIES_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/registries.conf
    - name: BUILD_REGISTRIES_DIR_PATH
      value: /var/run/configs/openshift.io/build-system/registries.d
    - name: BUILD_SIGNATURE_POLICY_PATH
      value: /var/run/configs/openshift.io/build-system/policy.json
    - name: BUILD_STORAGE_CONF_PATH
      value: /var/run/configs/openshift.io/build-system/storage.conf
    - name: BUILD_BLOBCACHE_DIR
      value: /var/cache/blobs
    - name: HTTP_PROXY
    - name: HTTPS_PROXY
    - name: NO_PROXY
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imagePullPolicy: IfNotPresent
    name: manage-dockerfile
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tmp/build
      name: buildworkdir
    - mountPath: /var/run/configs/openshift.io/build-system
      name: build-system-configs
      readOnly: true
    - mountPath: /var/run/configs/openshift.io/certs
      name: build-ca-bundles
    - mountPath: /etc/pki/ca-trust/extracted/pem
      name: build-proxy-ca-bundles
    - mountPath: /var/cache/blobs
      name: build-blob-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: builder-token-gv4x9
      readOnly: true
  nodeName: infra-01.osepext01.claro.amx
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: builder
  serviceAccountName: builder
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/containers/cache
      type: ""
    name: buildcachedir
  - emptyDir: {}
    name: buildworkdir
  - name: builder-dockercfg-jtvsh-push
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-jtvsh
  - name: builder-dockercfg-jtvsh-pull
    secret:
      defaultMode: 384
      secretName: builder-dockercfg-jtvsh
  - configMap:
      defaultMode: 420
      name: claro-mock-service-3-sys-config
    name: build-system-configs
  - configMap:
      defaultMode: 420
      items:
      - key: service-ca.crt
        path: certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt
      name: claro-mock-service-3-ca
    name: build-ca-bundles
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: claro-mock-service-3-global-ca
    name: build-proxy-ca-bundles
  - emptyDir: {}
    name: container-storage-root
  - emptyDir: {}
    name: build-blob-cache
  - name: builder-token-gv4x9
    secret:
      defaultMode: 420
      secretName: builder-token-gv4x9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:46:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:46:53Z"
    message: 'containers with unready status: [sti-build]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:46:53Z"
    message: 'containers with unready status: [sti-build]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-07T21:46:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://12797d6468535d532b3614f209366944a1f89c9af1c312ab3c03f40cdc60544a
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: sti-build
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://12797d6468535d532b3614f209366944a1f89c9af1c312ab3c03f40cdc60544a
        exitCode: 1
        finishedAt: "2020-09-07T21:46:52Z"
        message: |
          Caching blobs under "/var/cache/blobs".
          Getting image source signatures
          Copying blob sha256:5ccfe6e48f4f71d761b34c61586ac1808cca10bf7e543a3666b802f38625c5a9
          Copying blob sha256:95ba73f94fc8f4c85e9b37f9b95f4f15fda80446024f985171f454b03e194462
          Copying blob sha256:51e9f237b750efcda2d5755785cdb8dd080d51585ae35d368e4f9b29a11b1994
          Copying blob sha256:35875365be086462ee5d275b62cfc13046029a9a084880c18583b932a5b23632
          Copying blob sha256:6c85ac87d44df4b64d7c273886fc5aed55a28422df33dcb641884ffa419db218
          Copying config sha256:8af4fe9149f32a43d83ebf4f38a44447324e8bf9509bcffb9c6540c19c5af26d
          Writing manifest to image destination
          Storing signatures
          Generating dockerfile with builder image image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b
          STEP 1: FROM image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b
          STEP 2: LABEL "io.openshift.build.image"="image-registry.openshift-image-registry.svc:5000/openshift/fuse7-java-openshift@sha256:adc5b484c12f915309a95acb71890e4a1a8148d5dadd6cc22d0794cdab81557b"       "io.openshift.build.source-location"="/tmp/build/inputs"
          STEP 3: ENV OPENSHIFT_BUILD_NAME="claro-mock-service-3"     OPENSHIFT_BUILD_NAMESPACE="3scale-project"
          STEP 4: USER root
          STEP 5: COPY upload/src /tmp/src
          STEP 6: RUN chown -R 185:0 /tmp/src
          STEP 7: USER 185
          STEP 8: RUN /usr/local/s2i/assemble
          ==================================================================
          Starting S2I Java Build .....
          S2I source build with plain binaries detected
          Copying binaries from /tmp/src to /deployments ...
          cp: cannot stat '/tmp/src/*': No such file or directory
          Aborting due to error code 1 for copying /tmp/src to /deployments
          subprocess exited with status 1
          subprocess exited with status 1
          error: build error: error building at STEP "RUN /usr/local/s2i/assemble": exit status 1
        reason: Error
        startedAt: "2020-09-07T21:46:18Z"
  hostIP: 10.92.114.128
  initContainerStatuses:
  - containerID: cri-o://df77c45cfcea285e2e24f88c4ac4481a0c5502b0ebc319a79c502d03249fff21
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84289f9fd2d94a61c1f8df840fc2f8074aec5e380522577322fde652131c4c2d
    lastState: {}
    name: manage-dockerfile
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://df77c45cfcea285e2e24f88c4ac4481a0c5502b0ebc319a79c502d03249fff21
        exitCode: 0
        finishedAt: "2020-09-07T21:46:17Z"
        reason: Completed
        startedAt: "2020-09-07T21:46:17Z"
  phase: Failed
  podIP: 10.128.1.25
  podIPs:
  - ip: 10.128.1.25
  qosClass: Burstable
  startTime: "2020-09-07T21:46:13Z"
