apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.1.48"
          ],
          "dns": {},
          "default-route": [
              "10.128.0.1"
          ]
      }]
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for init
      container system-master-svc; cpu, memory limit for init container system-master-svc'
    openshift.io/deployment-config.latest-version: "4"
    openshift.io/deployment-config.name: system-sphinx
    openshift.io/deployment.name: system-sphinx-4
    openshift.io/scc: restricted
  creationTimestamp: "2020-08-11T18:05:46Z"
  generateName: system-sphinx-4-
  labels:
    app: 3scale-api-management
    deployment: system-sphinx-4
    deploymentConfig: system-sphinx
    deploymentconfig: system-sphinx
    node-role.kubernetes.io/worker: ""
    threescale_component: system
    threescale_component_element: sphinx
  name: system-sphinx-4-mtj2w
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: system-sphinx-4
    uid: c8003b61-913a-4c52-84a8-6c7ae4e5d3df
  resourceVersion: "216975633"
  selfLink: /api/v1/namespaces/3scale-project/pods/system-sphinx-4-mtj2w
  uid: 59b60144-79e9-4821-903b-fa8d095e7226
spec:
  containers:
  - args:
    - rake
    - openshift:thinking_sphinx:start
    env:
    - name: RAILS_ENV
      valueFrom:
        configMapKeyRef:
          key: RAILS_ENV
          name: system-environment
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          key: URL
          name: system-database
    - name: THINKING_SPHINX_ADDRESS
      value: 0.0.0.0
    - name: THINKING_SPHINX_CONFIGURATION_FILE
      value: db/sphinx/production.conf
    - name: THINKING_SPHINX_PID_FILE
      value: db/sphinx/searchd.pid
    - name: DELTA_INDEX_INTERVAL
      value: "5"
    - name: FULL_REINDEX_INTERVAL
      value: "60"
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          key: URL
          name: system-redis
    - name: MESSAGE_BUS_REDIS_URL
      valueFrom:
        secretKeyRef:
          key: MESSAGE_BUS_URL
          name: system-redis
    - name: REDIS_NAMESPACE
      valueFrom:
        secretKeyRef:
          key: NAMESPACE
          name: system-redis
    - name: MESSAGE_BUS_REDIS_NAMESPACE
      valueFrom:
        secretKeyRef:
          key: MESSAGE_BUS_NAMESPACE
          name: system-redis
    - name: REDIS_SENTINEL_HOSTS
      valueFrom:
        secretKeyRef:
          key: SENTINEL_HOSTS
          name: system-redis
    - name: REDIS_SENTINEL_ROLE
      valueFrom:
        secretKeyRef:
          key: SENTINEL_ROLE
          name: system-redis
    - name: MESSAGE_BUS_REDIS_SENTINEL_HOSTS
      valueFrom:
        secretKeyRef:
          key: MESSAGE_BUS_SENTINEL_HOSTS
          name: system-redis
    - name: MESSAGE_BUS_REDIS_SENTINEL_ROLE
      valueFrom:
        secretKeyRef:
          key: MESSAGE_BUS_SENTINEL_ROLE
          name: system-redis
    image: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 9306
      timeoutSeconds: 1
    name: system-sphinx
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 80m
        memory: 250Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/system/db/sphinx
      name: system-sphinx-database
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: amp-token-5cmpq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: threescale-registry-auth
  - name: amp-dockercfg-cvfh4
  initContainers:
  - command:
    - sh
    - -c
    - until $(curl --output /dev/null --silent --fail --head http://system-master:3000/status);
      do sleep $SLEEP_SECONDS; done
    env:
    - name: SLEEP_SECONDS
      value: "1"
    image: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    imagePullPolicy: Always
    name: system-master-svc
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: amp-token-5cmpq
      readOnly: true
  nodeName: infra-01.osepext01.claro.amx
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: amp
  serviceAccountName: amp
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: system-sphinx-database
  - name: amp-token-5cmpq
    secret:
      defaultMode: 420
      secretName: amp-token-5cmpq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:06:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:06:49Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:06:49Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:05:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://2cd4d4783b52a07f1e875ae6186e13b05e9fed8048221f83e1a7d7c733fd0348
    image: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    imageID: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    lastState: {}
    name: system-sphinx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-11T18:06:49Z"
  hostIP: 10.92.114.128
  initContainerStatuses:
  - containerID: cri-o://68b72c2317d80c8a0ef4daf661f4b29d182144792b77c3537f34438d4a75b19a
    image: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    imageID: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    lastState: {}
    name: system-master-svc
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://68b72c2317d80c8a0ef4daf661f4b29d182144792b77c3537f34438d4a75b19a
        exitCode: 0
        finishedAt: "2020-08-11T18:06:48Z"
        reason: Completed
        startedAt: "2020-08-11T18:06:48Z"
  phase: Running
  podIP: 10.128.1.48
  podIPs:
  - ip: 10.128.1.48
  qosClass: Burstable
  startTime: "2020-08-11T18:05:45Z"
