apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: ""
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      deployment; cpu, memory limit for container deployment'
    openshift.io/deployment-config.name: system-sidekiq
    openshift.io/deployment.name: system-sidekiq-4
    openshift.io/scc: restricted
  creationTimestamp: "2020-08-11T18:05:43Z"
  labels:
    openshift.io/deployer-pod-for.name: system-sidekiq-4
  name: system-sidekiq-4-deploy
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: v1
    kind: ReplicationController
    name: system-sidekiq-4
    uid: ac7320f1-9c6c-452d-a132-1e08b20e8efd
  resourceVersion: "216975993"
  selfLink: /api/v1/namespaces/3scale-project/pods/system-sidekiq-4-deploy
  uid: 59ba08fe-9256-424e-864e-823138485ec9
spec:
  activeDeadlineSeconds: 21600
  containers:
  - env:
    - name: OPENSHIFT_DEPLOYMENT_NAME
      value: system-sidekiq-4
    - name: OPENSHIFT_DEPLOYMENT_NAMESPACE
      value: 3scale-project
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imagePullPolicy: IfNotPresent
    name: deployment
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000710000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployer-token-679s7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: deployer-dockercfg-dl94k
  nodeName: worker-01.osepext01.claro.amx
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: deployer
  serviceAccountName: deployer
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: deployer-token-679s7
    secret:
      defaultMode: 420
      secretName: deployer-token-679s7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:05:42Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:07:09Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:07:09Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-11T18:05:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://dcd901388e3893fab0c0ed2bf325ba06f927a5320881878ba9c053fb33354df8
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21f5aad0f5ec400213b30d1182d1a2308300cedd3562ccbda500ecce82f8a9de
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://dcd901388e3893fab0c0ed2bf325ba06f927a5320881878ba9c053fb33354df8
        exitCode: 0
        finishedAt: "2020-08-11T18:07:08Z"
        reason: Completed
        startedAt: "2020-08-11T18:05:44Z"
  hostIP: 10.92.114.131
  phase: Succeeded
  podIP: 10.130.3.154
  podIPs:
  - ip: 10.130.3.154
  qosClass: Burstable
  startTime: "2020-08-11T18:05:42Z"
