apiVersion: v1
items:
- apiVersion: apps.3scale.net/v1alpha1
  kind: APIManager
  metadata:
    annotations:
      apps.3scale.net/apimanager-threescale-version: "2.8"
      apps.3scale.net/threescale-operator-version: 0.5.0
    creationTimestamp: "2020-07-27T13:05:49Z"
    generation: 5
    name: claro-apimanager-pelado
    namespace: 3scale-project
    resourceVersion: "264679229"
    selfLink: /apis/apps.3scale.net/v1alpha1/namespaces/3scale-project/apimanagers/claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  spec:
    apicast:
      managementAPI: status
      openSSLVerify: false
      productionSpec:
        replicas: 0
      registryURL: http://apicast-staging:8090/policies
      responseCodes: true
      stagingSpec:
        replicas: 0
    appLabel: 3scale-api-management
    backend:
      cronSpec:
        replicas: 1
      listenerSpec:
        replicas: 1
      workerSpec:
        replicas: 1
    highAvailability:
      enabled: true
    imageStreamTagImportInsecure: false
    resourceRequirementsEnabled: true
    system:
      appSpec:
        replicas: 1
      sidekiqSpec:
        replicas: 1
    tenantName: 3scale
    wildcardDomain: apps.osepext01.claro.amx
    zync:
      appSpec:
        replicas: 1
      queSpec:
        replicas: 1
  status:
    deployments:
      ready:
      - backend-cron
      - backend-listener
      - backend-worker
      - system-app
      - system-memcache
      - system-sidekiq
      - system-sphinx
      - zync
      - zync-database
      - zync-que
      stopped:
      - apicast-production
      - apicast-staging
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
