apiVersion: v1
imagePullSecrets:
- name: threescale-registry-auth
- name: amp-dockercfg-cvfh4
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-07-27T13:05:49Z"
  name: amp
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378347"
  selfLink: /api/v1/namespaces/3scale-project/serviceaccounts/amp
  uid: 4880817f-5411-42aa-9984-b37ac04fafff
secrets:
- name: amp-dockercfg-cvfh4
- name: amp-token-5cmpq
