apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2020-07-21T16:46:38Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: system-app
  resourceVersion: "198378375"
  selfLink: /api/v1/persistentvolumes/system-app
  uid: 1200c37e-5fcb-4723-bbde-6f22fcc14e23
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: system-storage
    namespace: 3scale-project
    resourceVersion: "198378371"
    uid: e8b45ecf-0362-47bb-9385-cc93f85ddf55
  nfs:
    path: /CMS_PRDE_p_openshift_apu
    server: 10.92.49.14
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
