apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2020-07-27T13:05:50Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
  name: system-storage
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378379"
  selfLink: /api/v1/namespaces/3scale-project/persistentvolumeclaims/system-storage
  uid: e8b45ecf-0362-47bb-9385-cc93f85ddf55
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  volumeName: system-app
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  phase: Bound
