apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-11T14:19:52Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-apicast-production-dev
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: apicast-production-dev
    uid: df2cbdb7-95f4-4885-a68e-f09348683a6d
  resourceVersion: "254094453"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-apicast-production-dev
  uid: 12eeee5b-71f6-4c71-a853-e9ed82f4073a
spec:
  clusterIP: 172.30.19.65
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-apicast-production-dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-09T20:05:20Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-apicast-staging-dev
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: apicast-staging-dev
    uid: ea443588-d7b9-41a1-8a06-2b20f3d40d13
  resourceVersion: "252198452"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-apicast-staging-dev
  uid: d7ed0d0f-2d0b-44c9-b92f-bb3c169a2f2f
spec:
  clusterIP: 172.30.140.94
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-apicast-staging-dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T15:18:19Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-dev-production
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: dev-production
    uid: 0a920910-34c4-4479-a8f9-4a7857c66a39
  resourceVersion: "257388453"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-dev-production
  uid: d84a86ce-dccf-4374-a93c-af259363fc52
spec:
  clusterIP: 172.30.17.189
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-dev-production
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T14:59:46Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-dev-staging
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: dev-staging
    uid: 6603a68f-0c67-41d3-bf52-309b8fc56bbb
  resourceVersion: "257374572"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-dev-staging
  uid: 5eac3e95-ac1f-4621-9be6-2e7726b4532b
spec:
  clusterIP: 172.30.117.240
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-dev-staging
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-09T20:05:19Z"
  labels:
    name: apicast-operator
  name: apicast-operator
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: apicast-operator
    uid: 0190f03e-38da-4f67-b25f-f19a1e54e5a5
  resourceVersion: "252198421"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-operator
  uid: 7b085055-43e1-4fb7-be51-cc298c404fb8
spec:
  clusterIP: 172.30.41.147
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: apicast-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T15:39:07Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-prod-production
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: prod-production
    uid: 22262456-4e76-4e69-95f0-ff99fe500efe
  resourceVersion: "257404461"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-prod-production
  uid: f7c8951b-5372-4c5f-84ff-12e79841761c
spec:
  clusterIP: 172.30.144.254
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-prod-production
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T15:30:20Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-prod-staging
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: prod-staging
    uid: 64e524e3-45e9-40c7-b973-00a812267b90
  resourceVersion: "257397712"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-prod-staging
  uid: df038c91-6d31-40f4-b8a6-e07264eafe34
spec:
  clusterIP: 172.30.233.187
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-prod-staging
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: apicast
    threescale_component_element: production
  name: apicast-production
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378446"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-production
  uid: 532aab9b-2de0-4f98-be96-22e9b89df62a
spec:
  clusterIP: 172.30.133.88
  ports:
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deploymentConfig: apicast-production
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: apicast
    threescale_component_element: staging
  name: apicast-staging
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378441"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-staging
  uid: f47211f4-279b-4f5f-980f-2c4a6db5a262
spec:
  clusterIP: 172.30.22.166
  ports:
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deploymentConfig: apicast-staging
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T15:27:20Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-test-production
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: test-production
    uid: f87a9d5f-526a-4ec7-9d78-51f4c5867336
  resourceVersion: "257395280"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-test-production
  uid: be93d369-4bee-40fb-a430-b4730286fcd8
spec:
  clusterIP: 172.30.104.61
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-test-production
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-14T15:25:34Z"
  labels:
    app: apicast
    threescale_component: apicast
  name: apicast-test-staging
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    controller: true
    kind: APIcast
    name: test-staging
    uid: 78f2ee67-ecfa-4c98-aafb-18d388ea3839
  resourceVersion: "257393891"
  selfLink: /api/v1/namespaces/3scale-project/services/apicast-test-staging
  uid: 74e6befd-e266-415b-8c52-299e42ba1bcb
spec:
  clusterIP: 172.30.252.144
  ports:
  - name: proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    deployment: apicast-test-staging
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: backend
    threescale_component_element: listener
  name: backend-listener
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378355"
  selfLink: /api/v1/namespaces/3scale-project/services/backend-listener
  uid: 6ddace11-9dd8-4afa-a49f-2a28e711c327
spec:
  clusterIP: 172.30.68.152
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentConfig: backend-listener
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-09-08T15:07:36Z"
  labels:
    app: book-service
  name: book-service
  namespace: 3scale-project
  resourceVersion: "254098216"
  selfLink: /api/v1/namespaces/3scale-project/services/book-service
  uid: bb1800ff-e7c2-4c7b-a9d7-a05b596164a6
spec:
  clusterIP: 172.30.96.68
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: book-service
    deploymentconfig: book-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-08T13:55:43Z"
  name: srvc-claro-mock-service
  namespace: 3scale-project
  resourceVersion: "250787635"
  selfLink: /api/v1/namespaces/3scale-project/services/srvc-claro-mock-service
  uid: 7149afbd-de72-490b-83d9-994890b243ce
spec:
  clusterIP: 172.30.88.50
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: claro-mock-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: developer-ui
  name: system-developer
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378383"
  selfLink: /api/v1/namespaces/3scale-project/services/system-developer
  uid: 088feb48-c3f4-4291-96fa-a3931ac26d70
spec:
  clusterIP: 172.30.46.143
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: developer
  selector:
    deploymentConfig: system-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: master-ui
  name: system-master
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378380"
  selfLink: /api/v1/namespaces/3scale-project/services/system-master
  uid: 963e3227-8297-4eb3-9c98-30c665a83ee9
spec:
  clusterIP: 172.30.253.72
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: master
  selector:
    deploymentConfig: system-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: memcache
  name: system-memcache
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378390"
  selfLink: /api/v1/namespaces/3scale-project/services/system-memcache
  uid: a6294806-4bf0-447b-be17-55997edd9d54
spec:
  clusterIP: 172.30.96.59
  ports:
  - name: memcache
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    deploymentConfig: system-memcache
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: provider-ui
  name: system-provider
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378374"
  selfLink: /api/v1/namespaces/3scale-project/services/system-provider
  uid: 046697dc-0cb8-4487-a6da-1fce77aa010f
spec:
  clusterIP: 172.30.118.50
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: provider
  selector:
    deploymentConfig: system-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: sphinx
  name: system-sphinx
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378386"
  selfLink: /api/v1/namespaces/3scale-project/services/system-sphinx
  uid: 6f551e71-e8b8-4462-8a78-ad30fff1ccca
spec:
  clusterIP: 172.30.157.230
  ports:
  - name: sphinx
    port: 9306
    protocol: TCP
    targetPort: 9306
  selector:
    deploymentConfig: system-sphinx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T12:57:11Z"
  labels:
    name: threescale-operator
  name: threescale-operator
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: 3scale-operator
    uid: c13bcf25-e504-4fb8-ada8-0457fb994ca6
  resourceVersion: "198370901"
  selfLink: /api/v1/namespaces/3scale-project/services/threescale-operator
  uid: 8ef80c17-e652-4387-a685-edf3a6bef18a
spec:
  clusterIP: 172.30.17.250
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: threescale-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: zync
  name: zync
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378428"
  selfLink: /api/v1/namespaces/3scale-project/services/zync
  uid: 1be3f1ff-8ee6-4442-9662-2ceff8d6d2aa
spec:
  clusterIP: 172.30.146.19
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: zync
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: zync
    threescale_component_element: database
  name: zync-database
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378432"
  selfLink: /api/v1/namespaces/3scale-project/services/zync-database
  uid: 286e40d3-1081-4b30-a32f-6256a1234c15
spec:
  clusterIP: 172.30.232.80
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deploymentConfig: zync-database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
