apiVersion: v1
data:
  AdminPortalURL: aHR0cHM6Ly8wM2IyZThiMzVjMjA4YTg4NWU3OGRhOGQ0ZDFkNDZjMTQ4YzNiMjc0ODU3OGNhMTAwOGE3OGRiZjAyODQ0MjhmQHByb2QtM3NjYWxlLWFkbWluLmFwcHMub3NlcGV4dDAxLmNsYXJvLmFteA==
kind: Secret
metadata:
  creationTimestamp: "2020-09-14T15:29:39Z"
  name: apicastprod-staging-secret
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIcast
    name: prod-staging
    uid: 64e524e3-45e9-40c7-b973-00a812267b90
  resourceVersion: "257397707"
  selfLink: /api/v1/namespaces/3scale-project/secrets/apicastprod-staging-secret
  uid: 6ee998a9-018e-449e-9f3c-384b6e04824a
type: Opaque
