apiVersion: v1
data:
  DBCP_GENERIC_CONN_AUTO_COMMIT: ZmFsc2U=
  DBCP_GENERIC_CONN_MAX_AGE_MS: NzIwMDAwMA==
  DBCP_GENERIC_CONN_MAX_WAIT_MS: NTAwMA==
  DBCP_GENERIC_CONN_VALIDATION_ON_GET: dHJ1ZQ==
  DBCP_GENERIC_CONN_VALIDATION_ORACLE: c2VsZWN0IDEgZnJvbSBkdWFs
  DBCP_GENERIC_POOL_MAX_SIZE_L1: NQ==
  DBCP_GENERIC_POOL_MAX_SIZE_L2: MTA=
  DBCP_GENERIC_POOL_MIN_SIZE: Mw==
kind: Secret
metadata:
  annotations:
    description: |-
      Propiedades genericas a nivel Database connection pool (prefix "DBCP_GENERIC_"):
        POOL_MIN_SIZE
             Minimo numero de conexiones en el pool.
        POOL_MAX_SIZE_L1
             Maximo numero de conexiones en el pool nivel 1.
        POOL_MAX_SIZE_L2
             Maximo numero de conexiones en el pool nivel 2.
        CONN_AUTO_COMMIT
             Seteo boolean de auto-commit de la conexion.
        CONN_MAX_WAIT_MS
             Maximo tiempo en ms a esperar si no hay conexiones disponibles en el pool.
        CONN_MAX_AGE_MS
             Maximo tiempo en ms que una conexion puede pertenecer al pool.
        CONN_VALIDATION_ON_GET
             Seteo boolean indicando que hay que validar el estado de una conexion cuando se la pide al pool.
        CONN_VALIDATION_ORACLE
             Query a usar para validar el estado de una conexion si la base de datos es Oracle.
  creationTimestamp: "2020-07-27T12:56:31Z"
  name: dbcp-generic
  namespace: 3scale-project
  resourceVersion: "198370304"
  selfLink: /api/v1/namespaces/3scale-project/secrets/dbcp-generic
  uid: 6ada942e-780a-41c6-8538-ba9ff36f3003
type: Opaque
