apiVersion: v1
data:
  PASSWORD: bGdYREJKV0w=
  URL: aHR0cDovL3N5c3RlbS1tYXN0ZXI6MzAwMC9tYXN0ZXIvZXZlbnRzL2ltcG9ydA==
kind: Secret
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
  name: system-events-hook
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378402"
  selfLink: /api/v1/namespaces/3scale-project/secrets/system-events-hook
  uid: 5ea91044-5825-4a27-9411-143493167712
type: Opaque
