apiVersion: v1
data:
  ACCESS_TOKEN: cWNORUk3cVA=
  BASE_URL: aHR0cDovL3FjTkVJN3FQQHN5c3RlbS1tYXN0ZXI6MzAwMA==
  PROXY_CONFIGS_ENDPOINT: aHR0cDovL3FjTkVJN3FQQHN5c3RlbS1tYXN0ZXI6MzAwMC9tYXN0ZXIvYXBpL3Byb3h5L2NvbmZpZ3M=
kind: Secret
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
  name: system-master-apicast
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378405"
  selfLink: /api/v1/namespaces/3scale-project/secrets/system-master-apicast
  uid: 5a8217a2-207e-4a7f-8107-f00b5c6faa03
type: Opaque
