apiVersion: v1
data:
  SERVERS: c3lzdGVtLW1lbWNhY2hlOjExMjEx
kind: Secret
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
  name: system-memcache
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378409"
  selfLink: /api/v1/namespaces/3scale-project/secrets/system-memcache
  uid: 898e8ca1-1e67-4494-ae48-558751f3fe3f
type: Opaque
