apiVersion: v1
data:
  MESSAGE_BUS_NAMESPACE: ""
  MESSAGE_BUS_SENTINEL_HOSTS: ""
  MESSAGE_BUS_SENTINEL_ROLE: ""
  MESSAGE_BUS_URL: cmVkaXM6Ly8xMC45Mi4xMTIuMjIzOjYzNzkvOA==
  NAMESPACE: ""
  SENTINEL_HOSTS: ""
  SENTINEL_ROLE: ""
  URL: cmVkaXM6Ly8xMC45Mi4xMTIuMjIzOjYzNzkvMQ==
kind: Secret
metadata:
  creationTimestamp: "2020-07-27T12:57:48Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
  name: system-redis
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378404"
  selfLink: /api/v1/namespaces/3scale-project/secrets/system-redis
  uid: f3ef6110-3772-45de-8f97-6920256d6e70
type: Opaque
