apiVersion: v1
data:
  address: ""
  authentication: ""
  domain: ""
  openssl.verify.mode: ""
  password: ""
  port: ""
  username: ""
kind: Secret
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: smtp
  name: system-smtp
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378400"
  selfLink: /api/v1/namespaces/3scale-project/secrets/system-smtp
  uid: e815d9fa-5ff2-45a0-a810-ff2007f1e440
type: Opaque
