apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3p5bmM6b1JFU2Z1eHJtNUJBYndFb0B6eW5jLWRhdGFiYXNlOjU0MzIvenluY19wcm9kdWN0aW9u
  SECRET_KEY_BASE: VWt2S081NjNjeklUa0sxTA==
  ZYNC_AUTHENTICATION_TOKEN: WlRIcVBCYkxIWVF1aVkwZQ==
  ZYNC_DATABASE_PASSWORD: b1JFU2Z1eHJtNUJBYndFbw==
kind: Secret
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  labels:
    app: 3scale-api-management
    threescale_component: zync
  name: zync
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198378433"
  selfLink: /api/v1/namespaces/3scale-project/secrets/zync
  uid: 9ae4cede-704a-4369-9895-c4a0a551baee
type: Opaque
