kind: Secret
apiVersion: v1
metadata:
  name: system-smtp
  namespace: 3scale-project
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: smtp
  ownerReferences:
    - apiVersion: apps.3scale.net/v1alpha1
      kind: APIManager
      name: claro-apimanager-pelado
      uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
      controller: true
      blockOwnerDeletion: true
data:
  address: ''
  authentication: ''
  domain: ''
  openssl.verify.mode: ''
  password: ''
  port: ''
  username: ''
type: Opaque
