apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: dev-production
  namespace: 3scale-project
spec:
  adminPortalCredentialsRef:
    name: apicastdev-production-secret 
  cacheConfigurationSeconds: 300
  configurationLoadMode: lazy
  deploymentEnvironment: staging
  loglevel: debug