apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: prod-production
  namespace: 3scale-project
spec:
  adminPortalCredentialsRef:
    name: apicastprod-production-secret
  cacheConfigurationSeconds: 300
  configurationLoadMode: boot
  deploymentEnvironment: production
  loglevel: info