apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2020-09-08 15:41:49 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-09-08 15:41:31 +0000 UTC
    openshift.io/deployer-pod.name: book-service-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: book-service
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"book-service","namespace":"3scale-project","selfLink":"/apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/book-service","uid":"c2ac3835-10b8-447f-9a04-84c18fd8d7f3","resourceVersion":"250880727","generation":2,"creationTimestamp":"2020-09-08T15:07:36Z","labels":{"app":"book-service"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["book-service"],"from":{"kind":"ImageStreamTag","namespace":"3scale-project","name":"book-service:latest"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/3scale-project/book-service@sha256:580fff8b679089ef830b1b128687a02bda68ae0f6f6d1320ee10ca7c937f8191"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"book-service","deploymentconfig":"book-service"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"book-service","deploymentconfig":"book-service"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"book-service","image":"image-registry.openshift-image-registry.svc:5000/3scale-project/book-service@sha256:580fff8b679089ef830b1b128687a02bda68ae0f6f6d1320ee10ca7c937f8191","ports":[{"containerPort":8181,"protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"512Mi"},"requests":{"cpu":"50m","memory":"256Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-09-08T15:07:36Z","lastTransitionTime":"2020-09-08T15:07:36Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: "2020-09-08T15:41:31Z"
  generation: 2
  labels:
    app: book-service
    openshift.io/deployment-config.name: book-service
  name: book-service-1
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: book-service
    uid: c2ac3835-10b8-447f-9a04-84c18fd8d7f3
  resourceVersion: "250880983"
  selfLink: /api/v1/namespaces/3scale-project/replicationcontrollers/book-service-1
  uid: c43e1655-8091-4046-beeb-8d9a68b52121
spec:
  replicas: 1
  selector:
    app: book-service
    deployment: book-service-1
    deploymentconfig: book-service
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: book-service
        openshift.io/deployment.name: book-service-1
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: book-service
        deployment: book-service-1
        deploymentconfig: book-service
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/3scale-project/book-service@sha256:580fff8b679089ef830b1b128687a02bda68ae0f6f6d1320ee10ca7c937f8191
        imagePullPolicy: Always
        name: book-service
        ports:
        - containerPort: 8181
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
