apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-09-08 13:12:10 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-09-08 13:07:42 +0000 UTC
    openshift.io/deployer-pod.name: claro-mock-service-dc-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: claro-mock-service-dc
    openshift.io/deployment.cancelled: "true"
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: newer deployment was found running
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"claro-mock-service-dc","namespace":"3scale-project","selfLink":"/apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/claro-mock-service-dc","uid":"fcbd970d-99c7-4be2-ad4f-afca15a19e04","resourceVersion":"250746722","generation":1,"creationTimestamp":"2020-09-08T13:07:42Z"},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"claro-mock-service"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"claro-mock-service"}},"spec":{"containers":[{"name":"claro-mock-service","image":"3scale-project/claro-mock-service","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":0,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: "2020-09-08T13:07:42Z"
  generation: 3
  labels:
    openshift.io/deployment-config.name: claro-mock-service-dc
  name: claro-mock-service-dc-1
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: claro-mock-service-dc
    uid: fcbd970d-99c7-4be2-ad4f-afca15a19e04
  resourceVersion: "250750683"
  selfLink: /api/v1/namespaces/3scale-project/replicationcontrollers/claro-mock-service-dc-1
  uid: dc75cc6b-1376-41ab-9a8b-6b0768f8200b
spec:
  replicas: 0
  selector:
    app: claro-mock-service
    deployment: claro-mock-service-dc-1
    deploymentconfig: claro-mock-service-dc
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: claro-mock-service-dc
        openshift.io/deployment.name: claro-mock-service-dc-1
      creationTimestamp: null
      labels:
        app: claro-mock-service
        deployment: claro-mock-service-dc-1
        deploymentconfig: claro-mock-service-dc
    spec:
      containers:
      - image: 3scale-project/claro-mock-service
        imagePullPolicy: Always
        name: claro-mock-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 0
