apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/original-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-07-27 13:06:38 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-07-27 13:05:53 +0000 UTC
    openshift.io/deployer-pod.name: system-memcache-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: system-memcache
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"system-memcache","namespace":"3scale-project","selfLink":"/apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/system-memcache","uid":"df1d1c60-d1ae-4f70-8caf-91ba2dd77a4b","resourceVersion":"198378611","generation":2,"creationTimestamp":"2020-07-27T13:05:50Z","labels":{"app":"3scale-api-management","threescale_component":"system","threescale_component_element":"memcache"},"ownerReferences":[{"apiVersion":"apps.3scale.net/v1alpha1","kind":"APIManager","name":"claro-apimanager-pelado","uid":"3d48e8a8-df41-4aa1-9516-43d087853cca","controller":true,"blockOwnerDeletion":true}]},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["memcache"],"from":{"kind":"ImageStreamTag","namespace":"3scale-project","name":"system-memcached:latest"},"lastTriggeredImage":"registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:2be57d773843135c0677e31d34b0cd24fa9dafc4ef1367521caa2bab7c6122e6"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"deploymentConfig":"system-memcache"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"3scale-api-management","deploymentConfig":"system-memcache","threescale_component":"system","threescale_component_element":"memcache"}},"spec":{"containers":[{"name":"memcache","image":"registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:2be57d773843135c0677e31d34b0cd24fa9dafc4ef1367521caa2bab7c6122e6","command":["memcached","-m","64"],"ports":[{"containerPort":11211,"protocol":"TCP"}],"resources":{"limits":{"cpu":"250m","memory":"96Mi"},"requests":{"cpu":"50m","memory":"64Mi"}},"livenessProbe":{"tcpSocket":{"port":11211},"initialDelaySeconds":10,"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"exec":{"command":["sh","-c","echo version | nc $HOSTNAME 11211 | grep VERSION"]},"initialDelaySeconds":10,"timeoutSeconds":5,"periodSeconds":30,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"amp","serviceAccount":"amp","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-07-27T13:05:50Z","lastTransitionTime":"2020-07-27T13:05:50Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: "2020-07-27T13:05:53Z"
  generation: 3
  labels:
    app: 3scale-api-management
    openshift.io/deployment-config.name: system-memcache
    threescale_component: system
    threescale_component_element: memcache
  name: system-memcache-1
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: system-memcache
    uid: df1d1c60-d1ae-4f70-8caf-91ba2dd77a4b
  resourceVersion: "198490935"
  selfLink: /api/v1/namespaces/3scale-project/replicationcontrollers/system-memcache-1
  uid: 90941aa4-ee35-4602-9514-24c95dd230a1
spec:
  replicas: 0
  selector:
    deployment: system-memcache-1
    deploymentConfig: system-memcache
    deploymentconfig: system-memcache
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: system-memcache
        openshift.io/deployment.name: system-memcache-1
      creationTimestamp: null
      labels:
        app: 3scale-api-management
        deployment: system-memcache-1
        deploymentConfig: system-memcache
        deploymentconfig: system-memcache
        threescale_component: system
        threescale_component_element: memcache
    spec:
      containers:
      - command:
        - memcached
        - -m
        - "64"
        image: registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:2be57d773843135c0677e31d34b0cd24fa9dafc4ef1367521caa2bab7c6122e6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 11211
          timeoutSeconds: 1
        name: memcache
        ports:
        - containerPort: 11211
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - echo version | nc $HOSTNAME 11211 | grep VERSION
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 96Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: amp
      serviceAccountName: amp
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 0
