apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2020-08-31T13:39:49Z"
  generation: 38
  labels:
    app: 3scale-api-management
    threescale_component: apicast
    threescale_component_element: production
  name: apicast-production
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "259737325"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/apicast-production
  uid: faa93aa1-2f0e-4734-ba36-491ec82052fe
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: apicast-production
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 1800
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        prometheus.io/port: "9421"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: 3scale-api-management
        deploymentConfig: apicast-production
        threescale_component: apicast
        threescale_component_element: production
    spec:
      containers:
      - env:
        - name: THREESCALE_PORTAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: PROXY_CONFIGS_ENDPOINT
              name: system-master-apicast
        - name: BACKEND_ENDPOINT_OVERRIDE
          valueFrom:
            secretKeyRef:
              key: service_endpoint
              name: backend-listener
        - name: APICAST_MANAGEMENT_API
          valueFrom:
            configMapKeyRef:
              key: APICAST_MANAGEMENT_API
              name: apicast-environment
        - name: OPENSSL_VERIFY
          valueFrom:
            configMapKeyRef:
              key: OPENSSL_VERIFY
              name: apicast-environment
        - name: APICAST_RESPONSE_CODES
          valueFrom:
            configMapKeyRef:
              key: APICAST_RESPONSE_CODES
              name: apicast-environment
        - name: APICAST_CONFIGURATION_LOADER
          value: boot
        - name: APICAST_CONFIGURATION_CACHE
          value: "300"
        - name: THREESCALE_DEPLOYMENT_ENV
          value: production
        image: image-registry.openshift-image-registry.svc:5000/3scale-project/amp-apicast@sha256:7e5d6f382e7e834e11609e5e43cdfeeb4a2e0923e8cf4b9d866e9833e0bb8863
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/live
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: apicast-production
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8090
          protocol: TCP
        - containerPort: 9421
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/ready
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until $(curl --output /dev/null --silent --fail --head http://system-master:3000/status);
          do sleep $SLEEP_SECONDS; done
        env:
        - name: SLEEP_SECONDS
          value: "1"
        image: image-registry.openshift-image-registry.svc:5000/3scale-project/amp-apicast@sha256:7e5d6f382e7e834e11609e5e43cdfeeb4a2e0923e8cf4b9d866e9833e0bb8863
        imagePullPolicy: Always
        name: system-master-svc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: amp
      serviceAccountName: amp
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - system-master-svc
      - apicast-production
      from:
        kind: ImageStreamTag
        name: amp-apicast:latest
        namespace: 3scale-project
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/3scale-project/amp-apicast@sha256:7e5d6f382e7e834e11609e5e43cdfeeb4a2e0923e8cf4b9d866e9833e0bb8863
    type: ImageChange
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: "2020-09-11T14:51:27Z"
    lastUpdateTime: "2020-09-11T14:51:27Z"
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  - lastTransitionTime: "2020-09-16T19:24:02Z"
    lastUpdateTime: "2020-09-16T19:24:02Z"
    message: replication controller "apicast-production-32" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: Manual
    message: manual change
  latestVersion: 32
  observedGeneration: 38
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
