apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  generation: 5
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: sidekiq
  name: system-sidekiq
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "264679227"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/system-sidekiq
  uid: a0e70fb0-b766-4010-a7e5-2ff90c824e4f
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: system-sidekiq
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 1200
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 3scale-api-management
        deploymentConfig: system-sidekiq
        node-role.kubernetes.io/worker: ""
        threescale_component: system
        threescale_component_element: sidekiq
    spec:
      containers:
      - args:
        - rake
        - sidekiq:worker
        - RAILS_MAX_THREADS=25
        env:
        - name: AMP_RELEASE
          valueFrom:
            configMapKeyRef:
              key: AMP_RELEASE
              name: system-environment
        - name: APICAST_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              key: APICAST_REGISTRY_URL
              name: system-environment
        - name: FORCE_SSL
          valueFrom:
            configMapKeyRef:
              key: FORCE_SSL
              name: system-environment
        - name: PROVIDER_PLAN
          valueFrom:
            configMapKeyRef:
              key: PROVIDER_PLAN
              name: system-environment
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              key: RAILS_ENV
              name: system-environment
        - name: RAILS_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: RAILS_LOG_LEVEL
              name: system-environment
        - name: RAILS_LOG_TO_STDOUT
          valueFrom:
            configMapKeyRef:
              key: RAILS_LOG_TO_STDOUT
              name: system-environment
        - name: SSL_CERT_DIR
          valueFrom:
            configMapKeyRef:
              key: SSL_CERT_DIR
              name: system-environment
        - name: THINKING_SPHINX_PORT
          valueFrom:
            configMapKeyRef:
              key: THINKING_SPHINX_PORT
              name: system-environment
        - name: THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE
          valueFrom:
            configMapKeyRef:
              key: THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE
              name: system-environment
        - name: THREESCALE_SUPERDOMAIN
          valueFrom:
            configMapKeyRef:
              key: THREESCALE_SUPERDOMAIN
              name: system-environment
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: URL
              name: system-database
        - name: MASTER_DOMAIN
          valueFrom:
            secretKeyRef:
              key: MASTER_DOMAIN
              name: system-seed
        - name: MASTER_USER
          valueFrom:
            secretKeyRef:
              key: MASTER_USER
              name: system-seed
        - name: MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MASTER_PASSWORD
              name: system-seed
        - name: ADMIN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: ADMIN_ACCESS_TOKEN
              name: system-seed
        - name: USER_LOGIN
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER
              name: system-seed
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ADMIN_PASSWORD
              name: system-seed
        - name: USER_EMAIL
          valueFrom:
            secretKeyRef:
              key: ADMIN_EMAIL
              name: system-seed
        - name: TENANT_NAME
          valueFrom:
            secretKeyRef:
              key: TENANT_NAME
              name: system-seed
        - name: THINKING_SPHINX_ADDRESS
          value: system-sphinx
        - name: THINKING_SPHINX_CONFIGURATION_FILE
          value: /tmp/sphinx.conf
        - name: EVENTS_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: system-events-hook
        - name: RECAPTCHA_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: PUBLIC_KEY
              name: system-recaptcha
        - name: RECAPTCHA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: PRIVATE_KEY
              name: system-recaptcha
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: system-app
        - name: MEMCACHE_SERVERS
          valueFrom:
            secretKeyRef:
              key: SERVERS
              name: system-memcache
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: URL
              name: system-redis
        - name: MESSAGE_BUS_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_URL
              name: system-redis
        - name: REDIS_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: NAMESPACE
              name: system-redis
        - name: MESSAGE_BUS_REDIS_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_NAMESPACE
              name: system-redis
        - name: REDIS_SENTINEL_HOSTS
          valueFrom:
            secretKeyRef:
              key: SENTINEL_HOSTS
              name: system-redis
        - name: REDIS_SENTINEL_ROLE
          valueFrom:
            secretKeyRef:
              key: SENTINEL_ROLE
              name: system-redis
        - name: MESSAGE_BUS_REDIS_SENTINEL_HOSTS
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_SENTINEL_HOSTS
              name: system-redis
        - name: MESSAGE_BUS_REDIS_SENTINEL_ROLE
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_SENTINEL_ROLE
              name: system-redis
        - name: BACKEND_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDIS_STORAGE_URL
              name: backend-redis
        - name: BACKEND_REDIS_SENTINEL_HOSTS
          valueFrom:
            secretKeyRef:
              key: REDIS_STORAGE_SENTINEL_HOSTS
              name: backend-redis
        - name: BACKEND_REDIS_SENTINEL_ROLE
          valueFrom:
            secretKeyRef:
              key: REDIS_STORAGE_SENTINEL_ROLE
              name: backend-redis
        - name: APICAST_BACKEND_ROOT_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: route_endpoint
              name: backend-listener
        - name: BACKEND_ROUTE
          valueFrom:
            secretKeyRef:
              key: route_endpoint
              name: backend-listener
        - name: SMTP_ADDRESS
          valueFrom:
            secretKeyRef:
              key: address
              name: system-smtp
        - name: SMTP_USER_NAME
          valueFrom:
            secretKeyRef:
              key: username
              name: system-smtp
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: system-smtp
        - name: SMTP_DOMAIN
          valueFrom:
            secretKeyRef:
              key: domain
              name: system-smtp
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: system-smtp
        - name: SMTP_AUTHENTICATION
          valueFrom:
            secretKeyRef:
              key: authentication
              name: system-smtp
        - name: SMTP_OPENSSL_VERIFY_MODE
          valueFrom:
            secretKeyRef:
              key: openssl.verify.mode
              name: system-smtp
        - name: APICAST_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: ACCESS_TOKEN
              name: system-master-apicast
        - name: ZYNC_AUTHENTICATION_TOKEN
          valueFrom:
            secretKeyRef:
              key: ZYNC_AUTHENTICATION_TOKEN
              name: zync
        - name: CONFIG_INTERNAL_API_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: backend-internal-api
        - name: CONFIG_INTERNAL_API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: backend-internal-api
        image: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
        imagePullPolicy: IfNotPresent
        name: system-sidekiq
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/system/public/system
          name: system-storage
        - mountPath: /tmp
          name: system-tmp
        - mountPath: /opt/system-extra-configs
          name: system-config
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - bash
        - -c
        - bundle exec sh -c "until rake boot:redis && curl --output /dev/null --silent
          --fail --head http://system-master:3000/status; do sleep $SLEEP_SECONDS;
          done"
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: URL
              name: system-redis
        - name: MESSAGE_BUS_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_URL
              name: system-redis
        - name: REDIS_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: NAMESPACE
              name: system-redis
        - name: MESSAGE_BUS_REDIS_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_NAMESPACE
              name: system-redis
        - name: REDIS_SENTINEL_HOSTS
          valueFrom:
            secretKeyRef:
              key: SENTINEL_HOSTS
              name: system-redis
        - name: REDIS_SENTINEL_ROLE
          valueFrom:
            secretKeyRef:
              key: SENTINEL_ROLE
              name: system-redis
        - name: MESSAGE_BUS_REDIS_SENTINEL_HOSTS
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_SENTINEL_HOSTS
              name: system-redis
        - name: MESSAGE_BUS_REDIS_SENTINEL_ROLE
          valueFrom:
            secretKeyRef:
              key: MESSAGE_BUS_SENTINEL_ROLE
              name: system-redis
        - name: SLEEP_SECONDS
          value: "1"
        image: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
        imagePullPolicy: Always
        name: check-svc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: amp
      serviceAccountName: amp
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: system-tmp
      - name: system-storage
        persistentVolumeClaim:
          claimName: system-storage
      - configMap:
          defaultMode: 420
          items:
          - key: zync.yml
            path: zync.yml
          - key: rolling_updates.yml
            path: rolling_updates.yml
          - key: service_discovery.yml
            path: service_discovery.yml
          name: system
        name: system-config
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - check-svc
      - system-sidekiq
      from:
        kind: ImageStreamTag
        name: amp-system:latest
        namespace: 3scale-project
      lastTriggeredImage: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-11T18:07:06Z"
    lastUpdateTime: "2020-08-11T18:07:09Z"
    message: replication controller "system-sidekiq-4" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-09-21T08:03:38Z"
    lastUpdateTime: "2020-09-21T08:03:38Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: registry.redhat.io/3scale-amp2/system-rhel7@sha256:29836068f71f53f88b75345055808106cb4620bf3d488bd458709936d716377f
      type: ImageChange
    message: image change
  latestVersion: 4
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
