apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2020-07-27T13:05:50Z"
  generation: 3
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: memcache
  name: system-memcache
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198490977"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/system-memcache
  uid: df1d1c60-d1ae-4f70-8caf-91ba2dd77a4b
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: system-memcache
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 3scale-api-management
        deploymentConfig: system-memcache
        node-role.kubernetes.io/worker: ""
        threescale_component: system
        threescale_component_element: memcache
    spec:
      containers:
      - command:
        - memcached
        - -m
        - "64"
        image: registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:2be57d773843135c0677e31d34b0cd24fa9dafc4ef1367521caa2bab7c6122e6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 11211
          timeoutSeconds: 1
        name: memcache
        ports:
        - containerPort: 11211
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - echo version | nc $HOSTNAME 11211 | grep VERSION
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 96Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: amp
      serviceAccountName: amp
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - memcache
      from:
        kind: ImageStreamTag
        name: system-memcached:latest
        namespace: 3scale-project
      lastTriggeredImage: registry.redhat.io/3scale-amp2/memcached-rhel7@sha256:2be57d773843135c0677e31d34b0cd24fa9dafc4ef1367521caa2bab7c6122e6
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-27T13:06:37Z"
    lastUpdateTime: "2020-07-27T13:06:37Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-27T15:15:50Z"
    lastUpdateTime: "2020-07-27T15:15:53Z"
    message: replication controller "system-memcache-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
