apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  generation: 3
  labels:
    app: 3scale-api-management
    node-role.kubernetes.io/worker: ""
    threescale_component: zync
    threescale_component_element: database
  name: zync-database
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "198503094"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/zync-database
  uid: 18b1f8a3-66ae-4df8-a511-fe68788d1261
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: zync-database
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 3scale-api-management
        deploymentConfig: zync-database
        node-role.kubernetes.io/worker: ""
        threescale_component: zync
        threescale_component_element: database
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: zync
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ZYNC_DATABASE_PASSWORD
              name: zync
        - name: POSTGRESQL_DATABASE
          value: zync_production
        image: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:de3ab628b403dc5eed986a7f392c34687bddafee7bdfccfd65cecf137ade3dfd
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U zync -q -d zync_production -c 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 2G
          requests:
            cpu: 50m
            memory: 250M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: zync-database-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: amp
      serviceAccountName: amp
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: zync-database-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgresql
      from:
        kind: ImageStreamTag
        name: zync-database-postgresql:latest
        namespace: 3scale-project
      lastTriggeredImage: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:de3ab628b403dc5eed986a7f392c34687bddafee7bdfccfd65cecf137ade3dfd
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-07-27T15:16:46Z"
    lastUpdateTime: "2020-07-27T15:21:44Z"
    message: replication controller "zync-database-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-07-27T15:29:20Z"
    lastUpdateTime: "2020-07-27T15:29:20Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
