apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2020-07-27T13:05:51Z"
  generation: 4
  labels:
    app: 3scale-api-management
    node-role.kubernetes.io/worker: ""
    threescale_component: zync
  name: zync-que
  namespace: 3scale-project
  ownerReferences:
  - apiVersion: apps.3scale.net/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: APIManager
    name: claro-apimanager-pelado
    uid: 3d48e8a8-df41-4aa1-9516-43d087853cca
  resourceVersion: "260712780"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3scale-project/deploymentconfigs/zync-que
  uid: 466152c8-1c88-42e0-83bb-45eb3d7fefe4
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: zync-que
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        prometheus.io/port: "9394"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: 3scale-api-management
        deploymentConfig: zync-que
        node-role.kubernetes.io/worker: ""
    spec:
      containers:
      - args:
        - -c
        - bundle exec rake 'que[--worker-count 10]'
        command:
        - /usr/bin/bash
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: zync
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: zync
        - name: ZYNC_AUTHENTICATION_TOKEN
          valueFrom:
            secretKeyRef:
              key: ZYNC_AUTHENTICATION_TOKEN
              name: zync
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: registry.redhat.io/3scale-amp2/zync-rhel7@sha256:f46b47b84450a81cb463b66dc86b91baf0dd60bdca275192925f6924b90a57bf
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9394
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        name: que
        ports:
        - containerPort: 9394
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 250M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zync-que-sa
      serviceAccountName: zync-que-sa
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - que
      from:
        kind: ImageStreamTag
        name: amp-zync:latest
        namespace: 3scale-project
      lastTriggeredImage: registry.redhat.io/3scale-amp2/zync-rhel7@sha256:f46b47b84450a81cb463b66dc86b91baf0dd60bdca275192925f6924b90a57bf
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-11T18:06:10Z"
    lastUpdateTime: "2020-08-11T18:06:12Z"
    message: replication controller "zync-que-3" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-09-17T16:51:56Z"
    lastUpdateTime: "2020-09-17T16:51:56Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: registry.redhat.io/3scale-amp2/zync-rhel7@sha256:f46b47b84450a81cb463b66dc86b91baf0dd60bdca275192925f6924b90a57bf
      type: ImageChange
    message: image change
  latestVersion: 3
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
